# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YndTG16TCpNfD1Qwxx9YQDxopDlkaVg6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# === 1. Ler o arquivo ===
df = pd.read_csv("recruitment_data.csv")

# === 2. Definir X (variáveis explicativas) e Y (variável alvo) ===
X = df.drop(columns=["HiringDecision"])
Y = df["HiringDecision"]

# Adicionar coluna de 1s (termo independente/intercepto)
X = np.c_[np.ones(X.shape[0]), X]

# === 3. Método 1: Critério dos Mínimos Quadrados ===
XT = X.T
w_mq = np.linalg.inv(XT @ X) @ XT @ Y

# === 4. Método 2: Matriz Pseudoinversa ===
w_pseudo = np.linalg.pinv(X) @ Y

# === 5. Comparar os resultados ===
colunas = ["Intercepto"] + list(df.drop(columns=["HiringDecision"]).columns)
resultados = pd.DataFrame({
    "Variável": colunas,
    "Peso_Mínimos_Quadrados": w_mq,
    "Peso_Pseudoinversa": w_pseudo
})

print("\nPesos calculados pelos dois métodos:")
print(resultados)

# === 6. (Opcional) Previsão e R² para cada modelo ===
Y_pred_mq = X @ w_mq
Y_pred_pseudo = X @ w_pseudo

def r2(y, y_pred):
    ss_res = np.sum((y - y_pred)**2)
    ss_tot = np.sum((y - np.mean(y))**2)
    return 1 - (ss_res / ss_tot)

print("\nR² (Mínimos Quadrados):", r2(Y, Y_pred_mq))
print("R² (Pseudoinversa):", r2(Y, Y_pred_pseudo))

# === 7. Gráfico comparando importâncias ===
plt.figure(figsize=(10, 6))
plt.bar(resultados["Variável"], resultados["Peso_Pseudoinversa"])
plt.title("Importância das variáveis na contratação (Pseudoinversa)")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Peso estimado")
plt.tight_layout()
plt.show()